### ISSUE TITLE
Use with home-manager ZSH plugins

### ISSUE THREAD

**Issue by nickrttn** [timbertson/nix-wrangle#8]
👋 

I'm fairly new to Nix and working on managing my shell environment with Nix/Home Manager. I've got my ZSH plugins defined through Home Manager's [programs.zsh.plugins](https://nix-community.github.io/home-manager/options.html#opt-programs.zsh.plugins), but I don't see the need there to lock these to a commit as most are fairly stable. So I went looking for some way to keep them updated to the latest commit in a certain branch and found `nix-wrangle`!

I was wondering if you would have a quick example on how to use `nix-wrangle` to keep these ZSH plugins updated to the latest commit? I'm not really familiar enough with Nix + Nix file syntax and modules yet to figure this out so even a short snippet would be a great help 😊 

Thanks in advance!

**Comment by timbertson** [comment]
Hello!

With many apologies, your issue made me realise I hadn't [announced](https://github.com/timbertson/nix-wrangle/commit/cc0c215cc2f9dbfee31c1b96527310c0168c449f) the fact that I've decided to stop maintaining this and to use [niv](https://github.com/nmattia/niv) instead.

If you follow `niv` documentation, I _believe_ from looking at those `zsh` examples you should be able to use e.g. `src = sources.example-plugin;` where `sources` is the result of importing niv's generated `sources.nix`
